### ISSUE TITLE
Homepage FAQ Title

### ISSUE THREAD

**Issue by inesiwadare** [miemma/emma#13]
The Title "Preguntas Frecuentes" in the tab "Cómo funciona" has a different word spacing than the other titles, the letters are too close to each other, we need to separate them a little. 

<img width="497" alt="screen shot 2016-08-08 at 11 28 52 am" src="https://cloud.githubusercontent.com/assets/17226545/17487634/4fa971b8-5d5b-11e6-9c37-2f8f9b3f4df3.png">

**Comment by MauricioDinki** [comment]
Its done
