### ISSUE TITLE
UI fixes in the Dashboard

### ISSUE THREAD

**Issue by inesiwadare** [miemma/emma#15]
**Suscripción TAB**
- [x] We need to add some lines to separate the different topics:
- First info
- Adulto mayor
- Emmas

**Historial TAB**
- [x] The titles are in black, and they're supposed to be in grey. 
- [x] It's not centered
- [ ] Can we use an example to fill those fields so we can see the way it'll look like?

**Emma's profile TAB**
- [ ] In the section "Conoce más de María del Pilar" the text box is too big, we have to make it smaller so the user doesn't have to read all along in the same page, just put more margin in both sides of the container.

Concepción's Profile TAB
- [x] In the profile, below the name Concepción there's a line, and it's ok there, but we have to move it a little so it doesn't touch the name. 
- [x] When you edit something from the medical information, the fields have to be a little more separated between them, they're too close to each other and the titles:

<img width="730" alt="screen shot 2016-08-08 at 11 40 55 am" src="https://cloud.githubusercontent.com/assets/17226545/17488034/11d883fe-5d5d-11e6-9d82-e16c1ecee768.png">
- [ ] How can the User edit the hobbies and Pasatiempos section?
- [ ]  In the Tab "Historial de pagos" the font is black (should be grey) and it's not separated right, the distribution between words should be the same in all of them.
  Also if we can have an example of how it will look like when it's filled.

<img width="845" alt="screen shot 2016-08-08 at 11 43 20 am" src="https://cloud.githubusercontent.com/assets/17226545/17488085/54ac672c-5d5d-11e6-9db5-678b4a7c04a1.png">
- [x] In the section "Modificar contraseña" the fields are too close to each other, we have to separate them also.

**Comment by AlanSanchezP** [comment]
@MauricioDinki Said that the user can't edit hobbies and interests
