### ISSUE TITLE
Changes on UX

### ISSUE THREAD

**Issue by MauricioDinki** [miemma/emma#19]
- [x]  Change link on buttons "Empezar ahora" to Signup view
- [x] Change title on signup view to "Registrate y agenda una llamda"
- [x] Limit of size on admin upload images to 5MB
- [x]  In admin, emmas section, not all files are required
- [x] When a user is logged in, change de name Dashboard (on the top right yellow rectangle) for "Ver perfil"
- [x] In admin, "información médica" is not a mandatory field.

**Comment by getmoremx** [comment]
@MauricioDinki are this changes on sandbox?

**Comment by MauricioDinki** [comment]
@amorenoh90 yes we have it

**Comment by getmoremx** [comment]
@MauricioDinki what is the status of this issue? Have we done the last 2 check-boxes?

**Comment by getmoremx** [comment]
@MauricioDinki what is the status of this issue? Have we done the last 2 check-boxes?

**Comment by MauricioDinki** [comment]
@amorenoh90 We have the last checkboxes in sandbox
