### ISSUE TITLE
Add Hellobar

### ISSUE THREAD

**Issue by getmoremx** [miemma/emma#37]
We need to add a bar that works for leading people to do certain action. 

Here are the instructions: 
Add the following bit of JavaScript at the end of each page (right before the closing </body> tag):

<script type="text/javascript" src="//my.hellobar.com/12ada82826cf8fd315845336946bf4c47f4c1dde.js"></script>

**Comment by AlanSanchezP** [comment]
I implemented the code given but I don't understand what it exactly does (nothing happens)

**Comment by getmoremx** [comment]
Lets discuss this issue on tomorrows meeting. Please remember to bring it up.
