### ISSUE TITLE
Blog - Theme tags & Search bar

### ISSUE THREAD

**Issue by inesiwadare** [miemma/emma#46]
We have to add new tags for different Themes and a search bar so users can search by tag.

**Comment by AlanSanchezP** [comment]
These features can be enabled from the wordpress admin (wp-admin/widgets.php). We only need to know how they should look. I attach some screenshots of the current appearance in the local server.
![captura de pantalla de 2017-01-28 15 41 57](https://cloud.githubusercontent.com/assets/8754996/22400069/f76dce42-e570-11e6-81e9-a7c6e0b8394f.png)
![captura de pantalla de 2017-01-28 15 42 41](https://cloud.githubusercontent.com/assets/8754996/22400068/f76dafd4-e570-11e6-9a89-775c5bd63084.png)
![captura de pantalla de 2017-01-28 15 42 49](https://cloud.githubusercontent.com/assets/8754996/22400070/f77252b4-e570-11e6-9cb3-8bdecc04302c.png)

**Comment by inesiwadare** [comment]
It's perfect. Let's just check what happens when you move the mouse over the tags. Does it turn yellow? it'll be nice.
