### ISSUE TITLE
Change the Prices

### ISSUE THREAD

**Issue by inesiwadare** [miemma/emma#47]
There's a new change in the price tag:
See comment below.

**Comment by inesiwadare** [comment]
There are 3 things that we have to change in this section:
1. The name of the Plans
2. The price of each plan
3. The quote at the end

<img width="690" alt="screen shot 2017-01-17 at 9 39 47 am" src="https://cloud.githubusercontent.com/assets/17226545/22027266/e8b44cea-dc98-11e6-966d-584f19ca9cc5.png">

1. It has to say "Plan Básico" Instead of Introductorio.
2. It has to say "$1,600 MXN Mensuales"
3. Instead of "Hasta ..." text, change it to: "2 hrs de acompañamiento semanales."
-

1. It has to say "Plan Mixto" Instead of Básico.
2. It has to say "$3,000 MXN Mensuales"
3. Instead of "Hasta ..." text, change it to: "4 hrs de acompañamiento semanales."
-

1. It remains the same name, only with Capital letters: "PRO"
2. It has to say "$4,400 MXN Mensuales"
3. Instead of "Hasta ..." text, change it to: "8 hrs de acompañamiento semanales."

**Comment by AlanSanchezP** [comment]
Names, prices and number of hours are dynamic and have to be changed using the django admin. We can just modify the text that complements that information.

**Comment by getmoremx** [comment]
Thats right, some things are dynamic but some others are not. The thing is
that the client wants that the price says that it is monthly but the hours
of service are weekly. We need to be clear with the user.
