### ISSUE TITLE
Add info in the Blog section

### ISSUE THREAD

**Issue by inesiwadare** [miemma/emma#54]
Above "Suscríbete" add this text:

Emma es un apoyo para tu familia también.
Aprende a cuidar mejor de tus seres queridos
A través de información relevante y escrita por nuestros fundadores.

**Comment by AlanSanchezP** [comment]
This can be done in the wordpress admin (there's a widget called 'Text')

http://blog.miemma.com/wp-admin/widgets.php

**Comment by getmoremx** [comment]
Can you do it please?
