### ISSUE TITLE
Responsive issues

### ISSUE THREAD

**Issue by inesiwadare** [miemma/emma#60]
- [x] Make initial button "Encuentra a tu Emma ideal" Smaller and make the video image bigger, they're too close together.
- [x] Make the How it work text boxes smallers and left aligned.
- [x] Footer: Align "Quieres ser parte de nuestra familia" and "envia tu solicitud" tu the left and move it closer to the edge. The center is ok, just move everything upper because we have a lot of empty space on the top. Finally on the right column, the menu (Quienes somos contacto and FAQ) has to be in the same line, they look weird. And the phone number shouldn't be cut out.

**Comment by AlanSanchezP** [comment]
Due to the width of the third column, it isn't possible to have the three links in the same line
